# RustScribe Configuration Example
#
# For user-specific settings (AWS credentials, etc.), copy this file to:
#   - macOS: ~/Library/Application Support/rustscribe/config.yaml
#   - Linux: ~/.config/rustscribe/config.yaml
#   - Windows: %APPDATA%\rustscribe\config.yaml
#
# For project-specific settings, copy to:
#   - .config/rustscribe.yaml

aws:
  # AWS credentials (alternatively use AWS CLI, environment variables, or IAM roles)
  access_key_id: "your-aws-access-key-id"
  secret_access_key: "your-aws-secret-access-key"
  
  # AWS region where your S3 bucket and Transcribe service are located
  region: "us-east-1"
  
  # S3 bucket for temporary audio file storage during transcription
  # Make sure this bucket exists and you have read/write permissions
  s3_bucket: "your-transcription-bucket"
  
  # Optional: prefix for S3 keys (helps organize files)
  s3_key_prefix: "transcriptions/"

  # Transcription settings
  transcription:
    # Default language for transcription (null = auto-detect)
    default_language: null
    
    # Default audio format for processing (mp3 recommended for speed)
    media_format: "mp3"
    
    # Sample rate for audio processing (Hz)
    # Higher = better quality, lower = faster processing
    sample_rate: 44100
    
    # Enable speaker identification by default
    speaker_identification: false
    
    # Maximum number of speakers to identify (2-10)
    max_speakers: 2

app:
  # Whether to keep audio files after transcription (default: false)
  keep_audio: false
  
  # Default language for transcription (null = auto-detect)
  # Examples: "en-US", "es-ES", "fr-FR", "de-DE", "ja-JP"
  default_language: null
  
  # Maximum number of concurrent transcription jobs (default: 3)
  max_concurrent_jobs: 3
  
  # Default output format when not specified
  # Options: text, json, srt, vtt, csv
  default_output_format: "text"
  
  # Directory for temporary files (null = system default)
  temp_dir: null

# External tool configurations
tools:
  # Path to yt-dlp binary (null = search in PATH)
  yt_dlp_path: null
  
  # Path to ffmpeg binary (null = search in PATH)
  ffmpeg_path: null
  
  # Path to ffprobe binary (null = search in PATH)
  ffprobe_path: null

# Logging configuration
logging:
  # Log level: error, warn, info, debug, trace
  level: "info"
  
  # Log to file (null = console only)
  file: null
  
  # Enable JSON logging format
  json: false 